### PR TITLE
Formatting && Linting CI and correct their errors

### PR DESCRIPTION
**Pull request by eggplants**
I have added formatting and linting CI and fixed their errors automatically (`cargo fmt && cargo clippy --fix`) and manually.

### CODE REVIEW

**Comment by eggplants** [comment]
https://github.com/KaiseiYokoyama/joycon-rs/runs/4425677364?check_suite_focus=true

```
error: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
  --> src/joycon/driver/rumble.rs:97:1
   |
97 | impl Into<[u8; 4]> for Rumble {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `-D clippy::from-over-into` implied by `-D warnings`
   = help: consider to implement `From<joycon::driver::rumble::Rumble>` instead
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into

error: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
  --> src/joycon/driver/joycon_features.rs:80:5
   |
80 |     impl Into<[u8; 4]> for IMUConfig {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider to implement `From<joycon::driver::joycon_features::imu_sensitivity::IMUConfig>` instead
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into

error: this `impl` can be derived
  --> src/joycon/driver/mod.rs:83:5
   |
83 | /     impl Default for GlobalPacketNumber {
84 | |         fn default() -> Self {
85 | |             GlobalPacketNumber(0x0)
86 | |         }
87 | |     }
   | |_____^
   |
   = note: `-D clippy::derivable-impls` implied by `-D warnings`
   = help: try annotating `joycon::driver::global_packet_number::GlobalPacketNumber` with `#[derive(Default)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls

error: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
   --> src/joycon/driver/mod.rs:100:5
    |
100 |     impl Into<u8> for GlobalPacketNumber {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider to implement `From<joycon::driver::global_packet_number::GlobalPacketNumber>` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into

error: match expression looks like `matches!` macro
  --> src/joycon/driver/simple_joycon_driver.rs:66:17
   |
66 | /                 match device {
67 | |                     JoyConDeviceType::ProCon => false,
68 | |                     _ => true,
69 | |                 }
   | |_________________^ help: try this: `!matches!(device, JoyConDeviceType::ProCon)`
   |
   = note: `-D clippy::match-like-matches-macro` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro

error: match expression looks like `matches!` macro
  --> src/joycon/driver/simple_joycon_driver.rs:79:13
   |
79 | /             match device.device_type() {
80 | |                 JoyConDeviceType::ProCon => false,
81 | |                 _ => true,
82 | |             }
   | |_____________^ help: try this: `!matches!(device.device_type(), JoyConDeviceType::ProCon)`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro

error: match expression looks like `matches!` macro
   --> src/joycon/driver/input_report_mode.rs:689:73
    |
689 |               let imf_enabled = driver.enabled_features().iter().any(|jf| match jf {
    |  _________________________________________________________________________^
690 | |                 JoyConFeature::IMUFeature(_) => true,
691 | |                 _ => false,
692 | |             });
    | |_____________^ help: try this: `matches!(jf, JoyConFeature::IMUFeature(_))`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro

error: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
   --> src/joycon/driver/lights.rs:124:5
    |
124 |     impl Into<u8> for u4 {
    |     ^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider to implement `From<joycon::driver::lights::home_button::u4>` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into

error: an implementation of `From` is preferred since it gives you `Into<_>` for free where the reverse isn't true
   --> src/joycon/driver/lights.rs:272:5
    |
272 |     impl Into<[u8; 25]> for LightEmittingPattern {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: consider to implement `From<joycon::driver::lights::home_button::LightEmittingPattern>` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into

error: could not compile `joycon-rs` due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Process completed with exit code 101.
```

**Comment by eggplants** [comment]
```
warning: this `impl` can be derived
  --> src/joycon/driver/mod.rs:83:5
   |
83 | /     impl Default for GlobalPacketNumber {
84 | |         fn default() -> Self {
85 | |             GlobalPacketNumber(0x0)
86 | |         }
87 | |     }
   | |_____^
   |
   = note: `#[warn(clippy::derivable_impls)]` on by default
   = help: try annotating `joycon::driver::global_packet_number::GlobalPacketNumber` with `#[derive(Default)]`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls

warning: `joycon-rs` (lib) generated 1 warning
```

**Comment by eggplants** [comment]
Useless?

https://github.com/KaiseiYokoyama/joycon-rs/blob/d22274f86fa7620f81102ee5e8fa280752851a05/src/lib.rs#L263-L269

```shellsession
$ cargo clippy --all-targets -- -D warnings
    Checking joycon-rs v0.6.3 (/Users/eggplants/prog/joycon-rs)
error: identical args used in this `assert_eq!` macro call
   --> src/lib.rs:271:20
    |
271 |         assert_eq!(2 + 2, 4);
    |                    ^^^^^^^^
    |
    = note: `#[deny(clippy::eq_op)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#eq_op

error: could not compile `joycon-rs` due to previous error
```

**Comment by eggplants** [comment]
Please squash commits when you merge this PR.

**Comment by KaiseiYokoyama** [comment]
Yes, its useless. It could be the preset text of `cargo new`. 

> Useless?
> 
> https://github.com/KaiseiYokoyama/joycon-rs/blob/d22274f86fa7620f81102ee5e8fa280752851a05/src/lib.rs#L263-L269
> 
> ```
> $ cargo clippy --all-targets -- -D warnings
>     Checking joycon-rs v0.6.3 (/Users/eggplants/prog/joycon-rs)
> error: identical args used in this `assert_eq!` macro call
>    --> src/lib.rs:271:20
>     |
> 271 |         assert_eq!(2 + 2, 4);
>     |                    ^^^^^^^^
>     |
>     = note: `#[deny(clippy::eq_op)]` on by default
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#eq_op
> 
> error: could not compile `joycon-rs` due to previous error
> ```

**Comment by eggplants** [comment]
Ready to merge.

**Pull request merged**
